
generate: ## Generate code
	dart run build_runner build --delete-conflicting-outputs

clean: ## clean all autogenerated files
	@echo "Deleting autogenerated files..."
	find . -maxdepth 20 -type f \( -name "*.g.dart" -o -name "*.mocks.dart" -o -name "*.freezed.dart" \) -delete

	@echo "Cleaning files..."
	dart run build_runner clean
	flutter clean

	@echo "Regenerating files again..."
	flutter pub get
	make generate

build_android: ## Build the project
	flutter build apk --release
build_ios: ## Build the project
	flutter build ios --release
build_web: ## Build the project
	flutter build web --release

build: ## Interactive build command
    @read -p "Enter platform (android/ios/web): " platform; \
    read -p "Enter build mode (debug/release/profile): " mode; \
    if [ "$$platform" = "android" ]; then \
        flutter build apk --$$mode; \
    elif [ "$$platform" = "ios" ]; then \
        flutter build ios --$$mode; \
    elif [ "$$platform" = "web" ]; then \
        flutter build web --$$mode; \
    else \
        echo "Invalid platform. Please choose android, ios, or web."; \
	fi
run: ## Run the project
	make clean
	flutter run --release