name: peibo_flutter_technical_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  cached_network_image: 3.4.1
  dio: 5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0
  logger: 2.5.0

dev_dependencies:
  build_runner: 2.4.15
  custom_lint: 0.7.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: 3.0.6
  json_serializable: 6.9.5
  mockito: 5.4.5

flutter:
  uses-material-design: true

  fonts:
    - family: K2D
      fonts:
        - asset: assets/fonts/K2D-Regular.ttf
        - asset: assets/fonts/K2D-Medium.ttf
          weight: 500
        - asset: assets/fonts/K2D-Bold.ttf
          weight: 600
              
  assets:
    - assets/
